# Generated by Django 3.2 on 2021-05-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification', models.CharField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Title', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('Course_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('Certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.certification', verbose_name='Certification')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('About', models.TextField()),
                ('School_acronym', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_Title', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('Unit_Code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('About', models.TextField()),
                ('Classes', models.IntegerField(blank=True, null=True)),
                ('Day_Time', models.DateTimeField(verbose_name='Date/Time')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('Dept_code', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='Courses')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.school', verbose_name='School')),
                ('Units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.unit', verbose_name='Units')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.school', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='certification',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.school', verbose_name='College'),
        ),
        migrations.AddField(
            model_name='certification',
            name='Study_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.level', verbose_name='Study Level'),
        ),
    ]
